@IsTest 
private class DatabaseLayerTest {
    @IsTest 
    static void shouldInitRealDmlObjectByDefault() {
        Assert.fail('You still need to build this test'); 
    }

    @IsTest
    static void shouldInitMockDmlObject() {
        Assert.fail('You still need to build this test'); 
    }

    @IsTest 
    static void shouldInitCustomDmlObject() {
        Assert.fail('You still need to build this test');
    }

    @IsTest 
    static void shouldSwitchToRealDmlObject() {
        Assert.fail('You still need to build this test'); 
    }

    @IsTest 
    static void shouldInitRealSoqlObjectByDefault() {
        Assert.fail('You still need to build this test'); 
    }

    @IsTest
    static void shouldInitMockSoqlObject() {
        Assert.fail('You still need to build this test'); 
    }

    @IsTest 
    static void shouldInitCustomSoqlObject() {
        Assert.fail('You still need to build this test');
    }

    @IsTest 
    static void shouldSwitchToRealSoqlObject() {
        Assert.fail('You still need to build this test'); 
    }

    @IsTest 
    static void shouldInitSoqlUsingQueryString() {
        Assert.fail('You still need to build this test'); 
    }
}