@IsTest 
private class DatabaseLayerTest {
    @IsTest 
    static void shouldReturnRealDmlObjectByDefault() {
        Assert.fail('You still need to build this test'); 
    }

    @IsTest
    static void shouldReturnMockDmlObject() {
        Assert.fail('You still need to build this test'); 
    }

    @IsTest 
    static void shouldReturnCustomDmlObject() {
        Assert.fail('You still need to build this test');
    }

    @IsTest 
    static void shouldSwitchToRealDmlObject() {
        Assert.fail('You still need to build this test'); 
    }

    @IsTest 
    static void shouldReturnRealSoqlObjectByDefault() {
        Assert.fail('You still need to build this test'); 
    }

    @IsTest
    static void shouldReturnMockSoqlObject() {
        Assert.fail('You still need to build this test'); 
    }

    @IsTest 
    static void shouldReturnCustomSoqlObject() {
        Assert.fail('You still need to build this test');
    }

    @IsTest 
    static void shouldSwitchToRealSoqlObject() {
        Assert.fail('You still need to build this test'); 
    }
}