name: "Report Errors"

inputs:
  actor:
    description: |
      The user who triggered the failing run. 
      Necessary since composite actions can't access to 'github' variables.
  repo:
    description: The

  run-id:
    description: The Id of the failed run.
    required: true
  token:
    description: |
      A github token with access to this repository. 
      Necessary since composite actions can't access to 'secrets' variables.
    required: true

runs:
  using: "composite"

  steps:
    - name: Authenticate Github CLI
      env:
        TOKEN: ${{ inputs.token }}
      shell: bash
      run: |
        # Authenticate to the 'gh' cli using the provided token:
        set -euo pipefail
        echo "🔐 Authenticating to the 'gh' cli..."
        gh auth login --with-token --hostname github.com --git-protocol https <<< "$TOKEN"

    - name: Get Run Details
      id: get-run
      env:
        RUN_ID: ${{ inputs.run-id }}
      shell: bash
      run: |
        # Get information about the failed run:
        set -euo pipefail
        echo "🔍 Querying failed run: $RUN_ID..."
        CMD="gh run view $RUN_ID --repo $GITHUB_REPOSITORY --json attempt,jobs,name,number,updatedAt,url,workflowName"
        echo "$CMD"
        RESPONSE=$(eval "$CMD" | jq)
        echo "::group::Response:"
        echo "$RESPONSE"
        echo "::endgroup::"
        # Unpack the response into individual output variables:
        ATTEMPT=$(echo "$RESPONSE" | jq -r '.attempt')
        echo "attempt=$ATTEMPT" >> "$GITHUB_OUTPUT"
        JOB_NUMBER=$(echo "$RESPONSE" | jq -r '.number')
        echo "job-number=$JOB_NUMBER" >> "$GITHUB_OUTPUT"
        WORKFLOW=$(echo "$RESPONSE" | jq -r '.workflowName')
        echo "workflow=$WORKFLOW" >> "$GITHUB_OUTPUT"
        # The last job is always the one that failed:
        JOB_OBJ=$(echo "$RESPONSE" | jq '.jobs | .[-1]')
        JOB_NAME=$(echo "$JOB_OBJ" | jq -r '.name')
        echo "job=$JOB_NAME" >> "$GITHUB_OUTPUT"
        URL=$(echo "$JOB_OBJ" | jq -r '.url')
        echo "url=$URL" >> "$GITHUB_OUTPUT"
        LAST_FAILED_STEP=$(echo "$JOB_OBJ" | jq -r '.steps | reverse | map(select(.conclusion == "failure")) | .[0].name // ""')
        echo "step=$LAST_FAILED_STEP" >> "$GITHUB_OUTPUT"

    - name: Generate Error Content
      id: generate-content
      shell: bash
      env:
        ACTOR: ${{ inputs.actor }}
        ATTEMPT: ${{ steps.get-run.outputs.attempt }}
        JOB_NAME: ${{ steps.get-run.outputs.job }}
        JOB_NUMBER: ${{ steps.get-run.outputs.job-number }}
        STEP: ${{ steps.get-run.outputs.step }}
        URL: ${{ steps.get-run.outputs.url }}
        WORKFLOW: ${{ steps.get-run.outputs.workflow }}
      run: |
        # Generate the issue's title and body
        set -euo pipefail
        echo "📝 Generating issue content..."
        # The 'title' is the unique key for existing issues
        TITLE="🚨 CI Failure: ${WORKFLOW} - ${JOB_NAME} - ${JOB_NUMBER}"
        echo "title=$TITLE" >> "$GITHUB_OUTPUT"
        echo "$TITLE"
        # The 'body' will be used in the issue description (if new) or comment (if existing)
        BODY=$(cat <<EOF
        ### 🚨 CI Job Failed
        The \`${WORKFLOW}\` workflow failed unexpectedly. See more details below:
        > **Workflow:** \`${WORKFLOW}\`
        > **Job:** \`${JOB_NAME}\`
        > **Step:** \`${STEP}\`
        > **Triggered By:** @${ACTOR}
        > **Run:** \`${JOB_NUMBER}\`
        > **Attempt:** \`${ATTEMPT}\`

        🔗 ${URL}
        EOF
        )
        printf "body<<EOF\n%s\nEOF\n" "$BODY" >> "$GITHUB_OUTPUT"
        echo "$BODY"

    - name: Get Existing Issue
      id: get-existing
      shell: bash
      env:
        TITLE: ${{ steps.generate-content.outputs.title }}
      run: |
        # Check to see if past attempts of the same workflow/job already created an issue:
        set -euo pipefail
        echo "🔍 Querying existing issues by title: '$TITLE'..."
        CMD="gh issue list --repo $GITHUB_REPOSITORY --search '\"$TITLE\" in:title' --state all --json closed,number,title"
        echo "$CMD"
        RESPONSE=$(eval "$CMD")
        echo "::group::Response:"
        echo "$RESPONSE" | jq
        echo "::endgroup::"
        ISSUE_OBJ=$(echo "$RESPONSE" | jq -c '.[] | select(.title == "'"$TITLE"'")')
        IS_CLOSED=$(echo "$ISSUE_OBJ" | jq -r '.closed')
        ISSUE_ID=$(echo "$ISSUE_OBJ" | jq -r '.number')
        # Set outputs:
        echo "is-closed=$IS_CLOSED" >> "$GITHUB_OUTPUT"
        echo "issue-id=$ISSUE_ID" >> "$GITHUB_OUTPUT"

    - name: Add Comment to Existing Issue
      if: ${{ steps.get-existing.outputs.issue-id != '' }}
      shell: bash
      env:
        ACTOR: ${{ inputs.actor }}
        BODY: ${{ steps.generate-content.outputs.body }}
        IS_CLOSED: ${{ steps.get-existing.outputs.is-closed }}
        ISSUE_ID: ${{ steps.get-existing.outputs.issue-id }}
      run: |
        # Comment on existing issue for subsuquent attempts of same failed workflow/job:
        set -euo pipefail
        # If the issue is closed, reopen it:
        if [[ "$IS_CLOSED" == "true" ]]; then
          echo "🔓 Reopening issue #$ISSUE_ID..."
          REOPEN_RESPONSE=$(gh issue reopen "$ISSUE_ID" --repo "$GITHUB_REPOSITORY" --comment "$BODY")
          echo "$REOPEN_RESPONSE"
        fi
        # Assign the actor to the issue:
        echo "Assigning $ACTOR to isse $ISSUE_ID..."
        ASSIGNMENT_RESPONSE=$(gh issue edit "$ISSUE_ID" --repo "$GITHUB_REPOSITORY" --add-assignee "$ACTOR")
        echo "$ASSIGNMENT_RESPONSE"
        # Post a comment:
        echo "💬 Adding comment to issue #$ISSUE_ID..."
        COMMENT_RESPONSE=$(gh issue comment "$ISSUE_ID" --repo "$GITHUB_REPOSITORY" --body "$BODY")
        echo "$COMMENT_RESPONSE"

    - name: Create Issue
      if: ${{ steps.get-existing.outputs.issue-id == '' }}
      shell: bash
      env:
        ACTOR: ${{ inputs.actor }}
        BODY: ${{ steps.generate-content.outputs.body }}
        TITLE: ${{ steps.generate-content.outputs.title }}
      run: |
        # Create a new issue, if no existing issues created for prior failed attempts:
        set -euo pipefail
        echo "🚧 Creating issue..."
        RESPONSE=$(gh issue create \
          --title "$TITLE" \
          --body "$(echo -e "$BODY")" \
          --label "ci-failure" \
          --repo "$GITHUB_REPOSITORY" \
          --assignee "$ACTOR")
        echo "$RESPONSE"
